module.exports = {
  NEW_FRIEND_REQUEST: 'newFriendRequest',
  ACCEPTED_FRIEND_REQUEST: 'acceptedFriendRequest',
  DECLINED_FRIEND_REQUEST: 'declinedFriendRequest',
  CANCELED_FRIEND_REQUEST: 'canceledFriendRequest',
  FOLLOWERS_UPDATES: 'followersUpdates',
  NEW_POST_COMMENT: 'newPostComment',
  NEW_MESSAGE: 'newMessage',
  DELETE_FRIEND: 'deleteFriend',
  DELETED_POST_COMMENT: 'deletedPostComment',
  THEY_COMMENT_ON_MY_POST: 'theyCommentOnMyPost',
  POST_LIKES_UPDATES: 'postLikesUpdates',
  THEY_LIKE_MY_POST: 'theyLikeMyPost',
  THEY_LIKE_MY_COMMENT: 'theyLikeMyComment',
  COMMENT_LIKES_UPDATES: 'commentLikesUpdates',
};
